config/routes.rb
Rails.application.routes.draw do
  root 'polls#index'

  resources :polls do
    collection do
      get 'filter/:filter', to: :index, as: :filter
    end
    resources :votes, only: [:create, :update, :destroy]
  end
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :votes, inverse_of: :poll, dependent: :delete_all

  validates_presence_of :title

  scope :recents, -> { order(created_at: :desc) }
  scope :most_voted, -> { 
    select('polls.*, COUNT(votes.poll_id) AS count_votes')
      .joins('LEFT JOIN votes ON votes.poll_id = polls.id')
      .group(:poll_id)
      .order('count_votes DESC')
  }
  scope :last_voted, -> { 
    select('polls.*, MAX(votes.created_at) AS last_voted')
      .joins('LEFT JOIN votes ON votes.poll_id = polls.id')
      .group(:poll_id)
      .order('last_voted DESC')
  }
  scope :no_voted, -> { includes(:votes).where( votes: { id: nil }) }

  def votes_size(answer)
    answer == :yes ? votes.yes_votes.size : votes.no_votes.size
  end

  def votes_percent(answer)
    total = votes_size(:yes) + votes_size(:no)
    if total > 0
      (votes_size(answer).to_f * 100.0 / total.to_f).round
    else
      0
    end
  end

  private
    def total_votes
      votes.size
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :poll, inverse_of: :votes, counter_cache: true

  scope :yes_votes, -> { where( answer: true) }
  scope :no_votes, -> { where( answer: false) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    if params[:filter].blank? || params[:filter] == :recents.to_s
      @polls = Poll.recents.page params[:page]
    elsif params[:filter] == :most_voted.to_s
      @polls = Poll.most_voted.page params[:page]
    elsif params[:filter] == :last_voted.to_s
      @polls = Poll.last_voted.page params[:page]
    elsif params[:filter] == :no_voted.to_s
      @polls = Poll.no_voted.page params[:page]
    end
  end
  
  def new
    @poll = Poll.new
  end

  def show
  end

  def create
    @poll = Poll.new(poll_params)
    @poll.save
    respond_with @poll
  end

  def update
    @poll.update(poll_params)
    respond_with @poll
  end

  def destroy
    @poll.destroy
    redirect_to polls_path
  end

  private
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def poll_params
      params.require(:poll).permit(:title, :description)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  respond_to :js, :html
  def create
    @poll = Poll.find(params[:poll_id])
    @poll.votes.create(vote_params)
    respond_with @poll do |format|
      format.js { render nothing: true }
    end
  end

  private
    def vote_params
      params.require(:vote).permit(:answer)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/_header.html.slim
    header.mdl-layout__header
      .mdl-layout__header-row
        .mdl-layout-title 
          = t ('app.name')
        .mdl-layout-spacer
        nav.mdl-navigation
          = link_to t('.nav.new_poll'), new_poll_path, class: 'mdl-navigation__link'
          = link_to t('.nav.newers'), filter_polls_path(:recents), class: 'mdl-navigation__link'
          = link_to t('.nav.most_voted'), filter_polls_path(:most_voted), class: 'mdl-navigation__link'
          = link_to t('.nav.last_voted'), filter_polls_path(:last_voted), class: 'mdl-navigation__link'
          = link_to t('.nav.no_voted'), filter_polls_path(:no_voted), class: 'mdl-navigation__link'
        .mdl-textfield.mdl-js-textfield.mdl-textfield--expandable.mdl-textfield--floating-label.mdl-textfield--align-right
          label.mdl-button.mdl-js-button.mdl-button--icon[for="fixed-header-drawer-exp"]
            i.material-icons
              | search
          .mdl-textfield__expandable-holder
            input#fixed-header-drawer-exp.mdl-textfield__input[type="text" name="sample"]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t ('app.name')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.mdl-color--grey-100.mdl-color-text--grey-700
    .mdl-layout__container
      .mdl-layout.mdl-js-layout.mdl-layout--fixed-header
      
        = render 'layouts/header'

        main.mdl-layout__content
          .page-content
            .mdl-grid
              .mdl-cell.mdl-cell--12-col
                = yield

app/views/polls/_form.html.slim
section.add-poll.align-center
  h2
    = t('.add')
  = form_for @poll do |f|
    .mdl-textfield.mdl-js-textfield
      = f.text_field :title, class: 'mdl-textfield__input'
      = f.label :title, class: 'mdl-textfield__label'
    .action
      = f.submit t('.create'), class: 'mdl-button mdl-js-button mdl-button--raised'

app/views/polls/_poll.html.slim
section.section-poll.mdl-shadow--2dp
  .mdl-grid
    .mdl-cell.mdl-cell--12-col.align-center
      .poll
        header.header-poll
          = t 'created_at'
          = time_tag poll.created_at
          = link_to poll_path(:id => poll.id), data: { confirm: I18n.t("are_you_sure") },
          :method => :delete, class: 'mdl-button mdl-js-button mdl-button--icon' do
            = content_tag(:i, 'delete', class: 'material-icons')
          .total_votes
            strong
              = t '.total_votes', count: poll.votes.size
        h3
          = link_to poll.title, poll

      .votes-result
        .vote_option
          = form_for([poll, poll.votes.build]) do |f|
            = f.hidden_field :answer, value: true
            = f.button :submit, class: 'vote_button yes_votes' do
              = t('yes')
              i.material-icons
                | thumb_up
        .vote_option 
          = form_for([poll, poll.votes.build]) do |f|
            = f.hidden_field :answer, value: false
            = f.button :submit, class: 'vote_button no_votes' do
              = t('no')
              i.material-icons
                | thumb_down
      .stats_container
        .stats.align-center.hide
          h4
            = t '.stats'
          .chart_container
            strong
              = poll.votes_percent :yes
              | %
            .chart.yes data={percent: poll.votes_percent(:yes)}
          .chart_container
            .chart.no data={percent: poll.votes_percent(:no)}
            strong
              = poll.votes_percent :no
              | %
          .people_voted
            span.yes
              strong
                = t '.yes_vote'
              = t '.people_voted', count:  poll.votes_size(:yes)
            span.no
              strong
                = t '.no_vote'
              = t '.people_voted', count:  poll.votes_size(:no)


        button.mdl-button.mdl-js-button.mdl-button--icon.btn_stats
          i.material-icons
            | more_horiz

app/views/polls/index.html.slim
- unless @polls.blank?
  = render @polls 
  .paginate_container.align-center
    = paginate @polls
- if @polls.blank?
  h2.no_polls.align-center
    = t('.no_polls')

app/views/polls/new.html.slim
= render 'form'

app/views/polls/show.html.slim
.align-center
  = link_to t('.back'), root_path
= render @poll